name: App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set target environment
        id: set-env
        run: |
          echo "DEPLOY_USER=${{ vars.PRODUCTION_USER }}" >> $GITHUB_ENV
          echo "DEPLOY_PATH=${{ vars.PRODUCTION_PATH }}" >> $GITHUB_ENV
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH and Pull Latest Code
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem $DEPLOY_USER@${{ vars.SERVER_IP }} << EOF
            set -e

            eval \$(ssh-agent)
            ssh-add ~/.ssh/github_mulyosyahidin

            cd ${DEPLOY_PATH}
            git pull origin ${{ github.ref_name }}

            composer install --no-dev
            npm install
            npm run build

            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan migrate --force
          EOF
